config/routes.rb
Rails.application.routes.draw do
  root to: 'animals#index'
  resources :animals do
    resources :sightings
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :sightings, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
    render :index
  end

  def new
    @animal = Animal.new
    render :new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    render :edit
  end

  def show
    @animal = Animal.find(params[:id])
    render :show
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

  private
    def animal_params
      params.require(:animal).permit(:name, :species)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new
    render :new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@animal)
    else
      render :new
    end
  end

  def show
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    render :show
  end

  def edit
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    render :edit
  end

  def update
    @sighting = Sighting.find(params[:id])
    if @sighting.update(sighting_params)
      redirect_to animal_path(@sighting.animal)
    else
      @animal = Animal.find(params[:animal_id])
      render :edit
    end
  end

  def destroy
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@sighting.animal)
  end

  private
    def sighting_params
      params.require(:sighting).permit(:latitude, :longitude, :date, :animal_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/edit.html.erb
<h1>Edit animal</h1>

<%= form_for @animal do |f |%>
  <%= f.label :species %>
  <%= f.text_field :species %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Return to animal list", animals_path %></p>

app/views/animals/index.html.erb
<h1>Animals</h1>

<% if @animals.any? %>
  <ul>
    <% @animals.each do |animal| %>
      <li><%= link_to animal.species, animal_path(animal) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no animals yet.</p>
<% end %>

<p><%= link_to "Create new animal", new_animal_path %></p>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= form_for @animal do |f| %>
  <%= f.label :species %>
  <%= f.text_field :species %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/animals/show.html.erb
<h1><%= @animal.species %></h1>
<h3><%= @animal.name %></h3>

<p><%= link_to "Edit", edit_animal_path(@animal) %></p>
<p><%= link_to "Delete", animal_path(@animal),
                      :data => {:confirm => "You sure?",
                                  :method => "delete"} %></p>

<% if @animal.sightings.any? %>
  <ul>

  <% @animal.sightings.each do |sighting|%>
    <li><%= link_to sighting.date, animal_sighting_path(@animal, sighting) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no sightings yet.</p>
<% end %>


<p><%= link_to "Create new sighting", new_animal_sighting_path(@animal) %></p>

<p><%= link_to "Return to animals", animals_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/edit.html.erb
<h1>Edit sighting:</h1>

<%= form_for [@animal, @sighting] do |f| %>
  <%= f.label :latitude %>
  <%= f.number_field :latitude, :step => any %>
  <%= f.label :longitude %>
  <%= f.number_field :longitude, :step => any %>
  <%= f.label :date %>
  <%= f.date_field :date, :required => true%>
  <p><%= f.submit %></p>
<% end %>

app/views/sightings/new.html.erb
<h1>Add a new sighting:</h1>

<%= form_for [@animal, @sighting] do |f| %>
  <%= f.label :latitude %>
  <%= f.number_field :latitude, :required => true, step: :any%>
  <%= f.label :longitude %>
  <%= f.number_field :longitude, :required => true, step: :any%>
  <%= f.label :date %>
  <%= f.date_field :date, :required => true%>
  <p><%= f.submit %></p>
<% end %>

app/views/sightings/show.html.erb
<h1>Latitude: <%= @sighting.latitude%></h1>
<h1>Longitude: <%= @sighting.longitude%></h1>
<h3>Date: <%= @sighting.date %></h3>

<p>Sightings</p>
<p><%= link_to "Edit sighting", edit_animal_sighting_path(@animal, @sighting) %></p>
<p><%= link_to "Delete sighting", animal_sighting_path(@animal, @sighting),
                        :data => {:confirm => "Are you sure?",
                                      :method => "delete"} %></p>

<p><%= link_to "Back to #{@animal.species}", animal_path(@animal) %></p>